# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='publicaciones/')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'publicaciones',
            },
        ),
    ]
