# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('correo', models.EmailField(db_index=True, max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('servicio', models.CharField(choices=[('Auditor', 'auditor'), ('Consultor', 'consultor'), ('Finanza', 'finanza'), ('Contable', 'contable')], default='', max_length=300)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.FileField(upload_to='reportes/')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'formulario_de_registros',
            },
        ),
    ]
